### ISSUE TITLE
new adress for cloned https://github.com/kustomzone/AppCentre

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zeronet-central#1]
- clone https://github.com/kustomzone/AppCentre
- add 0net-URL here

**Comment by dnelband** [comment]
http://127.0.0.1:43110/1FSoWkVg2zmcNrGAyt1uoDEF6S3kqeZtay

**Comment by dnelband** [comment]
http://127.0.0.1:43110/1NYDdJ2JqMHsuD1Seau87BfGKbwEPEft8r - new frontend for zeronet central
http://127.0.0.1:43110/1GnTA9B5JDSsAEk63LyDCQkbmoiFDSVxad - zeronet central cluster (still has old front end)

its not adding the cluster automatically yet, im taking care of that now
