### ISSUE TITLE
GRID: Add Info-Stuff to each tile (this is required to do sorting for those info numbers afterwards)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zeronet-central#5]
- no. of up-votes
- no. of down-votes
- no. of comments
- no. of favorites (represented by a star)
- no. of peers (if in cache)
- date updated (if in cache)

in the popup, allow to add comments and to vote each comment up/down

**Comment by dnelband** [comment]
done, unfortunately i dont have access to the updated date through the site list

**Comment by haschimoto** [comment]
- lets display "date added" instead of "date updated"
- move all newly added infos so far below each picture instead of above

**Comment by haschimoto** [comment]
lets forget the above comment, will close this ticket and add a new one :)
